# https://www.cms.gov/medicare/coding-billing/icd-10-codes/icd-9-cm-diagnosis-procedure-codes-abbreviated-and-full-code-titles
icd_9_chapters = {
    "I": {"block": "001-139",
          "title": "Infectious And Parasitic Diseases"},
    "II": {"block": "140-239",
           "title": "Neoplasms"},
    "III": {"block": "240-279",
            "title": "Endocrine, Nutritional And Metabolic Diseases, And Immunity Disorders"},
    "IV": {"block": "280-289",
           "title": "Diseases Of The Blood And Blood-Forming Organs"},
    "V": {"block": "290-319",
          "title": "Mental Disorders"},
    "VI": {"block": "320-389",
           "title": "Diseases Of The Nervous System And Sense Organs"},
    "VII": {"block": "390-459",
            "title": "Diseases Of The Circulatory System"},
    "VIII": {"block": "460-519",
             "title": "Diseases Of The Respiratory System"},
    "IX": {"block": "520-579",
           "title": "Diseases Of The Digestive System"},
    "X": {"block": "580-629",
          "title": "Diseases Of The Genitourinary System"},
    "XI": {"block": "630-679",
           "title": "Complications Of Pregnancy, Childbirth, And The Puerperium"},
    "XII": {"block": "680-709",
            "title": "Diseases Of The Skin And Subcutaneous Tissue"},
    "XIII": {"block": "710-739",
             "title": "Diseases Of The Musculoskeletal System And Connective Tissue"},
    "XIV": {"block": "740-759",
            "title": "Congenital Anomalies"},
    "XV": {"block": "760-779",
           "title": "Certain Conditions Originating In The Perinatal Period"},
    "XVI": {"block": "780-799",
            "title": "Symptoms, Signs, And Ill-Defined Conditions"},
    "XVII": {"block": "800-999",
             "title": "Injury And Poisoning"},
    "XVII-E": {"block": "E000-E999",
               "title": "Supplementary Classification Of External Causes Of Injury And Poisoning"},
    "XVII-V": {"block": "V01-V82",
               "title": "Supplementary Classification Of Factors Influencing Health Status And Contact With Health Services"},
    "XVII-M": {"block": "M8000-M9970",
               "title": "Morphology of Neoplasms"}
}
# https://www.cms.gov/medicare/coding-billing/icd-10-codes/2024-icd-10-cm
icd_10_chapters = {
    "I": {"block": "A00-B99",
          "title": "Certain infectious and parasitic diseases"},
    "II": {"block": "C00-D48",
           "title": "Neoplasms"},
    "III": {"block": "D50-D89",
            "title": "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism"},
    "IV": {"block": "E00-E90",
           "title": "Endocrine, nutritional and metabolic diseases"},
    "V": {"block": "F00-F99",
          "title": "Mental, Behavioral and Neurodevelopmental disorders"},
    "VI": {"block": "G00-G99",
           "title": "Diseases of the nervous system"},
    "VII": {"block": "H00-H59",
            "title": "Diseases of the eye and adnexa"},
    "VIII": {"block": "H60-H95",
             "title": "Diseases of the ear and mastoid process"},
    "IX": {"block": "I00-I99",
           "title": "Diseases of the circulatory system"},
    "X": {"block": "J00-J99",
          "title": "Diseases of the respiratory system"},
    "XI": {"block": "K00-K93",
           "title": "Diseases of the digestive system"},
    "XII": {"block": "L00-L99",
            "title": "Diseases of the skin and subcutaneous tissue"},
    "XIII": {"block": "M00-M99",
             "title": "Diseases of the musculoskeletal system and connective tissue"},
    "XIV": {"block": "N00-N99",
            "title": "Diseases of the genitourinary system"},
    "XV": {"block": "O00-O99",
           "title": "Pregnancy, childbirth and the puerperium"},
    "XVI": {"block": "P00-P96",
            "title": "Certain conditions originating in the perinatal period"},
    "XVII": {"block": "Q00-Q99",
             "title": "Congenital malformations, deformations and chromosomal abnormalities"},
    "XVIII": {"block": "R00-R99",
              "title": "Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified"},
    "XIX": {"block": "S00-T98",
            "title": "Injury, poisoning and certain other consequences of external causes"},
    "XX": {"block": "V00-Y98",
           "title": "External causes of morbidity"},
    "XXI": {"block": "Z00-Z99",
            "title": "Factors influencing health status and contact with health services"},
    "XXII": {"block": "U00-U99",
             "title": "Codes for special purposes"}
}
